What: Added a git diff validation after git push origin $MERGE_BRANCH in the automerge.yml workflow to check if the local branch has changes compared to the remote branch before creating the Pull Request.
Why:
This prevents unnecessary PR creation when there are no new changes in the merge branch, optimizing the workflow and reducing noise in the repository.

AGPMAT-43

diff --git a/.github/workflows/automerge.yml b/.github/workflows/automerge.yml
--- a/.github/workflows/automerge.yml
+++ b/.github/workflows/automerge.yml
@@ -4,9 +4,6 @@ on:
   workflow_dispatch:  # This allows for manual triggering.
   schedule:
     - cron: '0 0 * * 6'  # This sets the workflow to run every Saturday at midnight.
-  push:
-    branches:
-        - AGPMAT-43-fix-automerge-workflow
 
 jobs:
   create-branch-and-pr:
@@ -25,20 +22,30 @@ jobs:
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       run: | 
+        set -e
+
         # Check if the merge branch already exists
+
+        if git diff --quiet origin/main adsk_contrib/dev; then
+            echo "adsk_contrib/dev is updated with main, automerge not required"
+            exit 0
+        fi
 
         if ! git checkout "$MERGE_BRANCH"; then
             echo "Create new branch $MERGE_BRANCH"
             git checkout -b "$MERGE_BRANCH"
+        else
+            echo "Merge main into the existing $MERGE_BRANCH"
+            git merge main
         fi
 
         echo "push to $MERGE_BRANCH"
         git push origin "$MERGE_BRANCH"
-        echo "Create merge PR"
 
+        echo "Create merge PR"
         gh pr create \
             --title "Merge $MERGE_BRANCH into adsk_contrib/dev" \
             --body "Auto-created PR to merge $MERGE_BRANCH into adsk_contrib/dev" \
-            --head "$MERGE_BRANCH"\
+            --head "$MERGE_BRANCH" \
             --base adsk_contrib/dev \
             --reviewer "ashwinbhat,zicher3d,ppenenko"
